// Code generated by Kitex v0.16.1. DO NOT EDIT.

package authservice

import (
	"context"
	auth "example.com/micro-auth-demo/gateway/kitex_gen/auth"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Login(ctx context.Context, req *auth.LoginRequest, callOptions ...callopt.Option) (r *auth.TokenPair, err error)
	RefreshToken(ctx context.Context, req *auth.RefreshTokenRequest, callOptions ...callopt.Option) (r *auth.TokenPair, err error)
	ValidateToken(ctx context.Context, req *auth.ValidateTokenRequest, callOptions ...callopt.Option) (r *auth.ValidateTokenResponse, err error)
	Logout(ctx context.Context, req *auth.LogoutRequest, callOptions ...callopt.Option) (r *auth.CommonResponse, err error)
	LogoutAll(ctx context.Context, req *auth.LogoutAllRequest, callOptions ...callopt.Option) (r *auth.CommonResponse, err error)
	ListSessions(ctx context.Context, req *auth.ListSessionsRequest, callOptions ...callopt.Option) (r *auth.ListSessionsResponse, err error)
	RevokeSession(ctx context.Context, req *auth.RevokeSessionRequest, callOptions ...callopt.Option) (r *auth.CommonResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kAuthServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAuthServiceClient struct {
	*kClient
}

func (p *kAuthServiceClient) Login(ctx context.Context, req *auth.LoginRequest, callOptions ...callopt.Option) (r *auth.TokenPair, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, req)
}

func (p *kAuthServiceClient) RefreshToken(ctx context.Context, req *auth.RefreshTokenRequest, callOptions ...callopt.Option) (r *auth.TokenPair, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RefreshToken(ctx, req)
}

func (p *kAuthServiceClient) ValidateToken(ctx context.Context, req *auth.ValidateTokenRequest, callOptions ...callopt.Option) (r *auth.ValidateTokenResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ValidateToken(ctx, req)
}

func (p *kAuthServiceClient) Logout(ctx context.Context, req *auth.LogoutRequest, callOptions ...callopt.Option) (r *auth.CommonResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Logout(ctx, req)
}

func (p *kAuthServiceClient) LogoutAll(ctx context.Context, req *auth.LogoutAllRequest, callOptions ...callopt.Option) (r *auth.CommonResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.LogoutAll(ctx, req)
}

func (p *kAuthServiceClient) ListSessions(ctx context.Context, req *auth.ListSessionsRequest, callOptions ...callopt.Option) (r *auth.ListSessionsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListSessions(ctx, req)
}

func (p *kAuthServiceClient) RevokeSession(ctx context.Context, req *auth.RevokeSessionRequest, callOptions ...callopt.Option) (r *auth.CommonResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RevokeSession(ctx, req)
}
