// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package user

import (
	"context"
	"fmt"
)

type UserInfo struct {
	UserId   int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	Email    string `thrift:"email,2" frugal:"2,default,string" json:"email"`
	Nickname string `thrift:"nickname,3" frugal:"3,default,string" json:"nickname"`
}

func NewUserInfo() *UserInfo {
	return &UserInfo{}
}

func (p *UserInfo) InitDefault() {
}

func (p *UserInfo) GetUserId() (v int64) {
	return p.UserId
}

func (p *UserInfo) GetEmail() (v string) {
	return p.Email
}

func (p *UserInfo) GetNickname() (v string) {
	return p.Nickname
}
func (p *UserInfo) SetUserId(val int64) {
	p.UserId = val
}
func (p *UserInfo) SetEmail(val string) {
	p.Email = val
}
func (p *UserInfo) SetNickname(val string) {
	p.Nickname = val
}

func (p *UserInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserInfo(%+v)", *p)
}

var fieldIDToName_UserInfo = map[int16]string{
	1: "user_id",
	2: "email",
	3: "nickname",
}

type CreateUserRequest struct {
	Email    string `thrift:"email,1" frugal:"1,default,string" json:"email"`
	Nickname string `thrift:"nickname,2" frugal:"2,default,string" json:"nickname"`
	Password string `thrift:"password,3" frugal:"3,default,string" json:"password"`
}

func NewCreateUserRequest() *CreateUserRequest {
	return &CreateUserRequest{}
}

func (p *CreateUserRequest) InitDefault() {
}

func (p *CreateUserRequest) GetEmail() (v string) {
	return p.Email
}

func (p *CreateUserRequest) GetNickname() (v string) {
	return p.Nickname
}

func (p *CreateUserRequest) GetPassword() (v string) {
	return p.Password
}
func (p *CreateUserRequest) SetEmail(val string) {
	p.Email = val
}
func (p *CreateUserRequest) SetNickname(val string) {
	p.Nickname = val
}
func (p *CreateUserRequest) SetPassword(val string) {
	p.Password = val
}

func (p *CreateUserRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateUserRequest(%+v)", *p)
}

var fieldIDToName_CreateUserRequest = map[int16]string{
	1: "email",
	2: "nickname",
	3: "password",
}

type CreateUserResponse struct {
	User *UserInfo `thrift:"user,1" frugal:"1,default,UserInfo" json:"user"`
}

func NewCreateUserResponse() *CreateUserResponse {
	return &CreateUserResponse{}
}

func (p *CreateUserResponse) InitDefault() {
}

var CreateUserResponse_User_DEFAULT *UserInfo

func (p *CreateUserResponse) GetUser() (v *UserInfo) {
	if !p.IsSetUser() {
		return CreateUserResponse_User_DEFAULT
	}
	return p.User
}
func (p *CreateUserResponse) SetUser(val *UserInfo) {
	p.User = val
}

func (p *CreateUserResponse) IsSetUser() bool {
	return p.User != nil
}

func (p *CreateUserResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateUserResponse(%+v)", *p)
}

var fieldIDToName_CreateUserResponse = map[int16]string{
	1: "user",
}

type GetUserRequest struct {
	UserId int64 `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
}

func NewGetUserRequest() *GetUserRequest {
	return &GetUserRequest{}
}

func (p *GetUserRequest) InitDefault() {
}

func (p *GetUserRequest) GetUserId() (v int64) {
	return p.UserId
}
func (p *GetUserRequest) SetUserId(val int64) {
	p.UserId = val
}

func (p *GetUserRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserRequest(%+v)", *p)
}

var fieldIDToName_GetUserRequest = map[int16]string{
	1: "user_id",
}

type GetUserResponse struct {
	User *UserInfo `thrift:"user,1" frugal:"1,default,UserInfo" json:"user"`
}

func NewGetUserResponse() *GetUserResponse {
	return &GetUserResponse{}
}

func (p *GetUserResponse) InitDefault() {
}

var GetUserResponse_User_DEFAULT *UserInfo

func (p *GetUserResponse) GetUser() (v *UserInfo) {
	if !p.IsSetUser() {
		return GetUserResponse_User_DEFAULT
	}
	return p.User
}
func (p *GetUserResponse) SetUser(val *UserInfo) {
	p.User = val
}

func (p *GetUserResponse) IsSetUser() bool {
	return p.User != nil
}

func (p *GetUserResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserResponse(%+v)", *p)
}

var fieldIDToName_GetUserResponse = map[int16]string{
	1: "user",
}

type VerifyCredentialRequest struct {
	Email    string `thrift:"email,1" frugal:"1,default,string" json:"email"`
	Password string `thrift:"password,2" frugal:"2,default,string" json:"password"`
}

func NewVerifyCredentialRequest() *VerifyCredentialRequest {
	return &VerifyCredentialRequest{}
}

func (p *VerifyCredentialRequest) InitDefault() {
}

func (p *VerifyCredentialRequest) GetEmail() (v string) {
	return p.Email
}

func (p *VerifyCredentialRequest) GetPassword() (v string) {
	return p.Password
}
func (p *VerifyCredentialRequest) SetEmail(val string) {
	p.Email = val
}
func (p *VerifyCredentialRequest) SetPassword(val string) {
	p.Password = val
}

func (p *VerifyCredentialRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerifyCredentialRequest(%+v)", *p)
}

var fieldIDToName_VerifyCredentialRequest = map[int16]string{
	1: "email",
	2: "password",
}

type VerifyCredentialResponse struct {
	Ok     bool      `thrift:"ok,1" frugal:"1,default,bool" json:"ok"`
	User   *UserInfo `thrift:"user,2" frugal:"2,default,UserInfo" json:"user"`
	Reason string    `thrift:"reason,3" frugal:"3,default,string" json:"reason"`
}

func NewVerifyCredentialResponse() *VerifyCredentialResponse {
	return &VerifyCredentialResponse{}
}

func (p *VerifyCredentialResponse) InitDefault() {
}

func (p *VerifyCredentialResponse) GetOk() (v bool) {
	return p.Ok
}

var VerifyCredentialResponse_User_DEFAULT *UserInfo

func (p *VerifyCredentialResponse) GetUser() (v *UserInfo) {
	if !p.IsSetUser() {
		return VerifyCredentialResponse_User_DEFAULT
	}
	return p.User
}

func (p *VerifyCredentialResponse) GetReason() (v string) {
	return p.Reason
}
func (p *VerifyCredentialResponse) SetOk(val bool) {
	p.Ok = val
}
func (p *VerifyCredentialResponse) SetUser(val *UserInfo) {
	p.User = val
}
func (p *VerifyCredentialResponse) SetReason(val string) {
	p.Reason = val
}

func (p *VerifyCredentialResponse) IsSetUser() bool {
	return p.User != nil
}

func (p *VerifyCredentialResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerifyCredentialResponse(%+v)", *p)
}

var fieldIDToName_VerifyCredentialResponse = map[int16]string{
	1: "ok",
	2: "user",
	3: "reason",
}

type CheckPasswordRequest struct {
	UserId   int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	Password string `thrift:"password,2" frugal:"2,default,string" json:"password"`
}

func NewCheckPasswordRequest() *CheckPasswordRequest {
	return &CheckPasswordRequest{}
}

func (p *CheckPasswordRequest) InitDefault() {
}

func (p *CheckPasswordRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *CheckPasswordRequest) GetPassword() (v string) {
	return p.Password
}
func (p *CheckPasswordRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *CheckPasswordRequest) SetPassword(val string) {
	p.Password = val
}

func (p *CheckPasswordRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CheckPasswordRequest(%+v)", *p)
}

var fieldIDToName_CheckPasswordRequest = map[int16]string{
	1: "user_id",
	2: "password",
}

type CheckPasswordResponse struct {
	Ok bool `thrift:"ok,1" frugal:"1,default,bool" json:"ok"`
}

func NewCheckPasswordResponse() *CheckPasswordResponse {
	return &CheckPasswordResponse{}
}

func (p *CheckPasswordResponse) InitDefault() {
}

func (p *CheckPasswordResponse) GetOk() (v bool) {
	return p.Ok
}
func (p *CheckPasswordResponse) SetOk(val bool) {
	p.Ok = val
}

func (p *CheckPasswordResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CheckPasswordResponse(%+v)", *p)
}

var fieldIDToName_CheckPasswordResponse = map[int16]string{
	1: "ok",
}

type UserService interface {
	CreateUser(ctx context.Context, req *CreateUserRequest) (r *CreateUserResponse, err error)

	GetUser(ctx context.Context, req *GetUserRequest) (r *GetUserResponse, err error)

	VerifyCredential(ctx context.Context, req *VerifyCredentialRequest) (r *VerifyCredentialResponse, err error)

	CheckPassword(ctx context.Context, req *CheckPasswordRequest) (r *CheckPasswordResponse, err error)
}

type UserServiceCreateUserArgs struct {
	Req *CreateUserRequest `thrift:"req,1" frugal:"1,default,CreateUserRequest" json:"req"`
}

func NewUserServiceCreateUserArgs() *UserServiceCreateUserArgs {
	return &UserServiceCreateUserArgs{}
}

func (p *UserServiceCreateUserArgs) InitDefault() {
}

var UserServiceCreateUserArgs_Req_DEFAULT *CreateUserRequest

func (p *UserServiceCreateUserArgs) GetReq() (v *CreateUserRequest) {
	if !p.IsSetReq() {
		return UserServiceCreateUserArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceCreateUserArgs) SetReq(val *CreateUserRequest) {
	p.Req = val
}

func (p *UserServiceCreateUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceCreateUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceCreateUserArgs(%+v)", *p)
}

var fieldIDToName_UserServiceCreateUserArgs = map[int16]string{
	1: "req",
}

type UserServiceCreateUserResult struct {
	Success *CreateUserResponse `thrift:"success,0,optional" frugal:"0,optional,CreateUserResponse" json:"success,omitempty"`
}

func NewUserServiceCreateUserResult() *UserServiceCreateUserResult {
	return &UserServiceCreateUserResult{}
}

func (p *UserServiceCreateUserResult) InitDefault() {
}

var UserServiceCreateUserResult_Success_DEFAULT *CreateUserResponse

func (p *UserServiceCreateUserResult) GetSuccess() (v *CreateUserResponse) {
	if !p.IsSetSuccess() {
		return UserServiceCreateUserResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceCreateUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateUserResponse)
}

func (p *UserServiceCreateUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceCreateUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceCreateUserResult(%+v)", *p)
}

var fieldIDToName_UserServiceCreateUserResult = map[int16]string{
	0: "success",
}

type UserServiceGetUserArgs struct {
	Req *GetUserRequest `thrift:"req,1" frugal:"1,default,GetUserRequest" json:"req"`
}

func NewUserServiceGetUserArgs() *UserServiceGetUserArgs {
	return &UserServiceGetUserArgs{}
}

func (p *UserServiceGetUserArgs) InitDefault() {
}

var UserServiceGetUserArgs_Req_DEFAULT *GetUserRequest

func (p *UserServiceGetUserArgs) GetReq() (v *GetUserRequest) {
	if !p.IsSetReq() {
		return UserServiceGetUserArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceGetUserArgs) SetReq(val *GetUserRequest) {
	p.Req = val
}

func (p *UserServiceGetUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceGetUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserArgs(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserArgs = map[int16]string{
	1: "req",
}

type UserServiceGetUserResult struct {
	Success *GetUserResponse `thrift:"success,0,optional" frugal:"0,optional,GetUserResponse" json:"success,omitempty"`
}

func NewUserServiceGetUserResult() *UserServiceGetUserResult {
	return &UserServiceGetUserResult{}
}

func (p *UserServiceGetUserResult) InitDefault() {
}

var UserServiceGetUserResult_Success_DEFAULT *GetUserResponse

func (p *UserServiceGetUserResult) GetSuccess() (v *GetUserResponse) {
	if !p.IsSetSuccess() {
		return UserServiceGetUserResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetUserResponse)
}

func (p *UserServiceGetUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserResult(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserResult = map[int16]string{
	0: "success",
}

type UserServiceVerifyCredentialArgs struct {
	Req *VerifyCredentialRequest `thrift:"req,1" frugal:"1,default,VerifyCredentialRequest" json:"req"`
}

func NewUserServiceVerifyCredentialArgs() *UserServiceVerifyCredentialArgs {
	return &UserServiceVerifyCredentialArgs{}
}

func (p *UserServiceVerifyCredentialArgs) InitDefault() {
}

var UserServiceVerifyCredentialArgs_Req_DEFAULT *VerifyCredentialRequest

func (p *UserServiceVerifyCredentialArgs) GetReq() (v *VerifyCredentialRequest) {
	if !p.IsSetReq() {
		return UserServiceVerifyCredentialArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceVerifyCredentialArgs) SetReq(val *VerifyCredentialRequest) {
	p.Req = val
}

func (p *UserServiceVerifyCredentialArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceVerifyCredentialArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceVerifyCredentialArgs(%+v)", *p)
}

var fieldIDToName_UserServiceVerifyCredentialArgs = map[int16]string{
	1: "req",
}

type UserServiceVerifyCredentialResult struct {
	Success *VerifyCredentialResponse `thrift:"success,0,optional" frugal:"0,optional,VerifyCredentialResponse" json:"success,omitempty"`
}

func NewUserServiceVerifyCredentialResult() *UserServiceVerifyCredentialResult {
	return &UserServiceVerifyCredentialResult{}
}

func (p *UserServiceVerifyCredentialResult) InitDefault() {
}

var UserServiceVerifyCredentialResult_Success_DEFAULT *VerifyCredentialResponse

func (p *UserServiceVerifyCredentialResult) GetSuccess() (v *VerifyCredentialResponse) {
	if !p.IsSetSuccess() {
		return UserServiceVerifyCredentialResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceVerifyCredentialResult) SetSuccess(x interface{}) {
	p.Success = x.(*VerifyCredentialResponse)
}

func (p *UserServiceVerifyCredentialResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceVerifyCredentialResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceVerifyCredentialResult(%+v)", *p)
}

var fieldIDToName_UserServiceVerifyCredentialResult = map[int16]string{
	0: "success",
}

type UserServiceCheckPasswordArgs struct {
	Req *CheckPasswordRequest `thrift:"req,1" frugal:"1,default,CheckPasswordRequest" json:"req"`
}

func NewUserServiceCheckPasswordArgs() *UserServiceCheckPasswordArgs {
	return &UserServiceCheckPasswordArgs{}
}

func (p *UserServiceCheckPasswordArgs) InitDefault() {
}

var UserServiceCheckPasswordArgs_Req_DEFAULT *CheckPasswordRequest

func (p *UserServiceCheckPasswordArgs) GetReq() (v *CheckPasswordRequest) {
	if !p.IsSetReq() {
		return UserServiceCheckPasswordArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceCheckPasswordArgs) SetReq(val *CheckPasswordRequest) {
	p.Req = val
}

func (p *UserServiceCheckPasswordArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceCheckPasswordArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceCheckPasswordArgs(%+v)", *p)
}

var fieldIDToName_UserServiceCheckPasswordArgs = map[int16]string{
	1: "req",
}

type UserServiceCheckPasswordResult struct {
	Success *CheckPasswordResponse `thrift:"success,0,optional" frugal:"0,optional,CheckPasswordResponse" json:"success,omitempty"`
}

func NewUserServiceCheckPasswordResult() *UserServiceCheckPasswordResult {
	return &UserServiceCheckPasswordResult{}
}

func (p *UserServiceCheckPasswordResult) InitDefault() {
}

var UserServiceCheckPasswordResult_Success_DEFAULT *CheckPasswordResponse

func (p *UserServiceCheckPasswordResult) GetSuccess() (v *CheckPasswordResponse) {
	if !p.IsSetSuccess() {
		return UserServiceCheckPasswordResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceCheckPasswordResult) SetSuccess(x interface{}) {
	p.Success = x.(*CheckPasswordResponse)
}

func (p *UserServiceCheckPasswordResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceCheckPasswordResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceCheckPasswordResult(%+v)", *p)
}

var fieldIDToName_UserServiceCheckPasswordResult = map[int16]string{
	0: "success",
}
