// Code generated by Kitex v0.16.1. DO NOT EDIT.

package authservice

import (
	"context"
	"errors"
	auth "example.com/micro-auth-demo/auth-service/kitex_gen/auth"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Login": kitex.NewMethodInfo(
		loginHandler,
		newAuthServiceLoginArgs,
		newAuthServiceLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RefreshToken": kitex.NewMethodInfo(
		refreshTokenHandler,
		newAuthServiceRefreshTokenArgs,
		newAuthServiceRefreshTokenResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ValidateToken": kitex.NewMethodInfo(
		validateTokenHandler,
		newAuthServiceValidateTokenArgs,
		newAuthServiceValidateTokenResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Logout": kitex.NewMethodInfo(
		logoutHandler,
		newAuthServiceLogoutArgs,
		newAuthServiceLogoutResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"LogoutAll": kitex.NewMethodInfo(
		logoutAllHandler,
		newAuthServiceLogoutAllArgs,
		newAuthServiceLogoutAllResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListSessions": kitex.NewMethodInfo(
		listSessionsHandler,
		newAuthServiceListSessionsArgs,
		newAuthServiceListSessionsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RevokeSession": kitex.NewMethodInfo(
		revokeSessionHandler,
		newAuthServiceRevokeSessionArgs,
		newAuthServiceRevokeSessionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	authServiceServiceInfo                = NewServiceInfo()
	authServiceServiceInfoForClient       = NewServiceInfoForClient()
	authServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return authServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return authServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return authServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "AuthService"
	handlerType := (*auth.AuthService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "auth",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func loginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*auth.AuthServiceLoginArgs)
	realResult := result.(*auth.AuthServiceLoginResult)
	success, err := handler.(auth.AuthService).Login(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAuthServiceLoginArgs() interface{} {
	return auth.NewAuthServiceLoginArgs()
}

func newAuthServiceLoginResult() interface{} {
	return auth.NewAuthServiceLoginResult()
}

func refreshTokenHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*auth.AuthServiceRefreshTokenArgs)
	realResult := result.(*auth.AuthServiceRefreshTokenResult)
	success, err := handler.(auth.AuthService).RefreshToken(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAuthServiceRefreshTokenArgs() interface{} {
	return auth.NewAuthServiceRefreshTokenArgs()
}

func newAuthServiceRefreshTokenResult() interface{} {
	return auth.NewAuthServiceRefreshTokenResult()
}

func validateTokenHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*auth.AuthServiceValidateTokenArgs)
	realResult := result.(*auth.AuthServiceValidateTokenResult)
	success, err := handler.(auth.AuthService).ValidateToken(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAuthServiceValidateTokenArgs() interface{} {
	return auth.NewAuthServiceValidateTokenArgs()
}

func newAuthServiceValidateTokenResult() interface{} {
	return auth.NewAuthServiceValidateTokenResult()
}

func logoutHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*auth.AuthServiceLogoutArgs)
	realResult := result.(*auth.AuthServiceLogoutResult)
	success, err := handler.(auth.AuthService).Logout(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAuthServiceLogoutArgs() interface{} {
	return auth.NewAuthServiceLogoutArgs()
}

func newAuthServiceLogoutResult() interface{} {
	return auth.NewAuthServiceLogoutResult()
}

func logoutAllHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*auth.AuthServiceLogoutAllArgs)
	realResult := result.(*auth.AuthServiceLogoutAllResult)
	success, err := handler.(auth.AuthService).LogoutAll(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAuthServiceLogoutAllArgs() interface{} {
	return auth.NewAuthServiceLogoutAllArgs()
}

func newAuthServiceLogoutAllResult() interface{} {
	return auth.NewAuthServiceLogoutAllResult()
}

func listSessionsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*auth.AuthServiceListSessionsArgs)
	realResult := result.(*auth.AuthServiceListSessionsResult)
	success, err := handler.(auth.AuthService).ListSessions(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAuthServiceListSessionsArgs() interface{} {
	return auth.NewAuthServiceListSessionsArgs()
}

func newAuthServiceListSessionsResult() interface{} {
	return auth.NewAuthServiceListSessionsResult()
}

func revokeSessionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*auth.AuthServiceRevokeSessionArgs)
	realResult := result.(*auth.AuthServiceRevokeSessionResult)
	success, err := handler.(auth.AuthService).RevokeSession(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAuthServiceRevokeSessionArgs() interface{} {
	return auth.NewAuthServiceRevokeSessionArgs()
}

func newAuthServiceRevokeSessionResult() interface{} {
	return auth.NewAuthServiceRevokeSessionResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Login(ctx context.Context, req *auth.LoginRequest) (r *auth.TokenPair, err error) {
	var _args auth.AuthServiceLoginArgs
	_args.Req = req
	var _result auth.AuthServiceLoginResult
	if err = p.c.Call(ctx, "Login", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RefreshToken(ctx context.Context, req *auth.RefreshTokenRequest) (r *auth.TokenPair, err error) {
	var _args auth.AuthServiceRefreshTokenArgs
	_args.Req = req
	var _result auth.AuthServiceRefreshTokenResult
	if err = p.c.Call(ctx, "RefreshToken", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ValidateToken(ctx context.Context, req *auth.ValidateTokenRequest) (r *auth.ValidateTokenResponse, err error) {
	var _args auth.AuthServiceValidateTokenArgs
	_args.Req = req
	var _result auth.AuthServiceValidateTokenResult
	if err = p.c.Call(ctx, "ValidateToken", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Logout(ctx context.Context, req *auth.LogoutRequest) (r *auth.CommonResponse, err error) {
	var _args auth.AuthServiceLogoutArgs
	_args.Req = req
	var _result auth.AuthServiceLogoutResult
	if err = p.c.Call(ctx, "Logout", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) LogoutAll(ctx context.Context, req *auth.LogoutAllRequest) (r *auth.CommonResponse, err error) {
	var _args auth.AuthServiceLogoutAllArgs
	_args.Req = req
	var _result auth.AuthServiceLogoutAllResult
	if err = p.c.Call(ctx, "LogoutAll", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListSessions(ctx context.Context, req *auth.ListSessionsRequest) (r *auth.ListSessionsResponse, err error) {
	var _args auth.AuthServiceListSessionsArgs
	_args.Req = req
	var _result auth.AuthServiceListSessionsResult
	if err = p.c.Call(ctx, "ListSessions", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RevokeSession(ctx context.Context, req *auth.RevokeSessionRequest) (r *auth.CommonResponse, err error) {
	var _args auth.AuthServiceRevokeSessionArgs
	_args.Req = req
	var _result auth.AuthServiceRevokeSessionResult
	if err = p.c.Call(ctx, "RevokeSession", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
