FROM golang:1.25-alpine AS build

WORKDIR /app
RUN apk add --no-cache git ca-certificates

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags="-s -w" -o server .

FROM alpine:3.20

WORKDIR /app

RUN apk add --no-cache ca-certificates tzdata && update-ca-certificates

COPY --from=build /app/server /app/server
COPY --from=build /app/migrations /app/migrations
COPY --from=build /app/static /app/static

EXPOSE 8080

ENTRYPOINT ["/app/server"]