// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package auth

import (
	"context"
	"fmt"
)

type LoginRequest struct {
	Email      string `thrift:"email,1" frugal:"1,default,string" json:"email"`
	Password   string `thrift:"password,2" frugal:"2,default,string" json:"password"`
	DeviceId   string `thrift:"device_id,3" frugal:"3,default,string" json:"device_id"`
	DeviceName string `thrift:"device_name,4" frugal:"4,default,string" json:"device_name"`
	UserAgent  string `thrift:"user_agent,5" frugal:"5,default,string" json:"user_agent"`
	Ip         string `thrift:"ip,6" frugal:"6,default,string" json:"ip"`
}

func NewLoginRequest() *LoginRequest {
	return &LoginRequest{}
}

func (p *LoginRequest) InitDefault() {
}

func (p *LoginRequest) GetEmail() (v string) {
	return p.Email
}

func (p *LoginRequest) GetPassword() (v string) {
	return p.Password
}

func (p *LoginRequest) GetDeviceId() (v string) {
	return p.DeviceId
}

func (p *LoginRequest) GetDeviceName() (v string) {
	return p.DeviceName
}

func (p *LoginRequest) GetUserAgent() (v string) {
	return p.UserAgent
}

func (p *LoginRequest) GetIp() (v string) {
	return p.Ip
}
func (p *LoginRequest) SetEmail(val string) {
	p.Email = val
}
func (p *LoginRequest) SetPassword(val string) {
	p.Password = val
}
func (p *LoginRequest) SetDeviceId(val string) {
	p.DeviceId = val
}
func (p *LoginRequest) SetDeviceName(val string) {
	p.DeviceName = val
}
func (p *LoginRequest) SetUserAgent(val string) {
	p.UserAgent = val
}
func (p *LoginRequest) SetIp(val string) {
	p.Ip = val
}

func (p *LoginRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginRequest(%+v)", *p)
}

var fieldIDToName_LoginRequest = map[int16]string{
	1: "email",
	2: "password",
	3: "device_id",
	4: "device_name",
	5: "user_agent",
	6: "ip",
}

type TokenPair struct {
	AccessToken      string `thrift:"access_token,1" frugal:"1,default,string" json:"access_token"`
	RefreshToken     string `thrift:"refresh_token,2" frugal:"2,default,string" json:"refresh_token"`
	SessionId        string `thrift:"session_id,3" frugal:"3,default,string" json:"session_id"`
	AccessExpiresAt  int64  `thrift:"access_expires_at,4" frugal:"4,default,i64" json:"access_expires_at"`
	RefreshExpiresAt int64  `thrift:"refresh_expires_at,5" frugal:"5,default,i64" json:"refresh_expires_at"`
}

func NewTokenPair() *TokenPair {
	return &TokenPair{}
}

func (p *TokenPair) InitDefault() {
}

func (p *TokenPair) GetAccessToken() (v string) {
	return p.AccessToken
}

func (p *TokenPair) GetRefreshToken() (v string) {
	return p.RefreshToken
}

func (p *TokenPair) GetSessionId() (v string) {
	return p.SessionId
}

func (p *TokenPair) GetAccessExpiresAt() (v int64) {
	return p.AccessExpiresAt
}

func (p *TokenPair) GetRefreshExpiresAt() (v int64) {
	return p.RefreshExpiresAt
}
func (p *TokenPair) SetAccessToken(val string) {
	p.AccessToken = val
}
func (p *TokenPair) SetRefreshToken(val string) {
	p.RefreshToken = val
}
func (p *TokenPair) SetSessionId(val string) {
	p.SessionId = val
}
func (p *TokenPair) SetAccessExpiresAt(val int64) {
	p.AccessExpiresAt = val
}
func (p *TokenPair) SetRefreshExpiresAt(val int64) {
	p.RefreshExpiresAt = val
}

func (p *TokenPair) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TokenPair(%+v)", *p)
}

var fieldIDToName_TokenPair = map[int16]string{
	1: "access_token",
	2: "refresh_token",
	3: "session_id",
	4: "access_expires_at",
	5: "refresh_expires_at",
}

type RefreshTokenRequest struct {
	RefreshToken string `thrift:"refresh_token,1" frugal:"1,default,string" json:"refresh_token"`
	DeviceId     string `thrift:"device_id,2" frugal:"2,default,string" json:"device_id"`
	UserAgent    string `thrift:"user_agent,3" frugal:"3,default,string" json:"user_agent"`
	Ip           string `thrift:"ip,4" frugal:"4,default,string" json:"ip"`
}

func NewRefreshTokenRequest() *RefreshTokenRequest {
	return &RefreshTokenRequest{}
}

func (p *RefreshTokenRequest) InitDefault() {
}

func (p *RefreshTokenRequest) GetRefreshToken() (v string) {
	return p.RefreshToken
}

func (p *RefreshTokenRequest) GetDeviceId() (v string) {
	return p.DeviceId
}

func (p *RefreshTokenRequest) GetUserAgent() (v string) {
	return p.UserAgent
}

func (p *RefreshTokenRequest) GetIp() (v string) {
	return p.Ip
}
func (p *RefreshTokenRequest) SetRefreshToken(val string) {
	p.RefreshToken = val
}
func (p *RefreshTokenRequest) SetDeviceId(val string) {
	p.DeviceId = val
}
func (p *RefreshTokenRequest) SetUserAgent(val string) {
	p.UserAgent = val
}
func (p *RefreshTokenRequest) SetIp(val string) {
	p.Ip = val
}

func (p *RefreshTokenRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefreshTokenRequest(%+v)", *p)
}

var fieldIDToName_RefreshTokenRequest = map[int16]string{
	1: "refresh_token",
	2: "device_id",
	3: "user_agent",
	4: "ip",
}

type ValidateTokenRequest struct {
	AccessToken string `thrift:"access_token,1" frugal:"1,default,string" json:"access_token"`
}

func NewValidateTokenRequest() *ValidateTokenRequest {
	return &ValidateTokenRequest{}
}

func (p *ValidateTokenRequest) InitDefault() {
}

func (p *ValidateTokenRequest) GetAccessToken() (v string) {
	return p.AccessToken
}
func (p *ValidateTokenRequest) SetAccessToken(val string) {
	p.AccessToken = val
}

func (p *ValidateTokenRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ValidateTokenRequest(%+v)", *p)
}

var fieldIDToName_ValidateTokenRequest = map[int16]string{
	1: "access_token",
}

type ValidateTokenResponse struct {
	Valid     bool   `thrift:"valid,1" frugal:"1,default,bool" json:"valid"`
	UserId    int64  `thrift:"user_id,2" frugal:"2,default,i64" json:"user_id"`
	SessionId string `thrift:"session_id,3" frugal:"3,default,string" json:"session_id"`
	Reason    string `thrift:"reason,4" frugal:"4,default,string" json:"reason"`
}

func NewValidateTokenResponse() *ValidateTokenResponse {
	return &ValidateTokenResponse{}
}

func (p *ValidateTokenResponse) InitDefault() {
}

func (p *ValidateTokenResponse) GetValid() (v bool) {
	return p.Valid
}

func (p *ValidateTokenResponse) GetUserId() (v int64) {
	return p.UserId
}

func (p *ValidateTokenResponse) GetSessionId() (v string) {
	return p.SessionId
}

func (p *ValidateTokenResponse) GetReason() (v string) {
	return p.Reason
}
func (p *ValidateTokenResponse) SetValid(val bool) {
	p.Valid = val
}
func (p *ValidateTokenResponse) SetUserId(val int64) {
	p.UserId = val
}
func (p *ValidateTokenResponse) SetSessionId(val string) {
	p.SessionId = val
}
func (p *ValidateTokenResponse) SetReason(val string) {
	p.Reason = val
}

func (p *ValidateTokenResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ValidateTokenResponse(%+v)", *p)
}

var fieldIDToName_ValidateTokenResponse = map[int16]string{
	1: "valid",
	2: "user_id",
	3: "session_id",
	4: "reason",
}

type CommonResponse struct {
	Success bool   `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Message string `thrift:"message,2" frugal:"2,default,string" json:"message"`
}

func NewCommonResponse() *CommonResponse {
	return &CommonResponse{}
}

func (p *CommonResponse) InitDefault() {
}

func (p *CommonResponse) GetSuccess() (v bool) {
	return p.Success
}

func (p *CommonResponse) GetMessage() (v string) {
	return p.Message
}
func (p *CommonResponse) SetSuccess(val bool) {
	p.Success = val
}
func (p *CommonResponse) SetMessage(val string) {
	p.Message = val
}

func (p *CommonResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CommonResponse(%+v)", *p)
}

var fieldIDToName_CommonResponse = map[int16]string{
	1: "success",
	2: "message",
}

type LogoutRequest struct {
	AccessToken string `thrift:"access_token,1" frugal:"1,default,string" json:"access_token"`
}

func NewLogoutRequest() *LogoutRequest {
	return &LogoutRequest{}
}

func (p *LogoutRequest) InitDefault() {
}

func (p *LogoutRequest) GetAccessToken() (v string) {
	return p.AccessToken
}
func (p *LogoutRequest) SetAccessToken(val string) {
	p.AccessToken = val
}

func (p *LogoutRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LogoutRequest(%+v)", *p)
}

var fieldIDToName_LogoutRequest = map[int16]string{
	1: "access_token",
}

type LogoutAllRequest struct {
	UserId   int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	Password string `thrift:"password,2" frugal:"2,default,string" json:"password"`
}

func NewLogoutAllRequest() *LogoutAllRequest {
	return &LogoutAllRequest{}
}

func (p *LogoutAllRequest) InitDefault() {
}

func (p *LogoutAllRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *LogoutAllRequest) GetPassword() (v string) {
	return p.Password
}
func (p *LogoutAllRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *LogoutAllRequest) SetPassword(val string) {
	p.Password = val
}

func (p *LogoutAllRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LogoutAllRequest(%+v)", *p)
}

var fieldIDToName_LogoutAllRequest = map[int16]string{
	1: "user_id",
	2: "password",
}

type SessionInfo struct {
	SessionId  string `thrift:"session_id,1" frugal:"1,default,string" json:"session_id"`
	DeviceId   string `thrift:"device_id,2" frugal:"2,default,string" json:"device_id"`
	DeviceName string `thrift:"device_name,3" frugal:"3,default,string" json:"device_name"`
	UserAgent  string `thrift:"user_agent,4" frugal:"4,default,string" json:"user_agent"`
	LoginIp    string `thrift:"login_ip,5" frugal:"5,default,string" json:"login_ip"`
	LastIp     string `thrift:"last_ip,6" frugal:"6,default,string" json:"last_ip"`
	Status     string `thrift:"status,7" frugal:"7,default,string" json:"status"`
	Current    bool   `thrift:"current,8" frugal:"8,default,bool" json:"current"`
	CreatedAt  int64  `thrift:"created_at,9" frugal:"9,default,i64" json:"created_at"`
	LastSeenAt int64  `thrift:"last_seen_at,10" frugal:"10,default,i64" json:"last_seen_at"`
}

func NewSessionInfo() *SessionInfo {
	return &SessionInfo{}
}

func (p *SessionInfo) InitDefault() {
}

func (p *SessionInfo) GetSessionId() (v string) {
	return p.SessionId
}

func (p *SessionInfo) GetDeviceId() (v string) {
	return p.DeviceId
}

func (p *SessionInfo) GetDeviceName() (v string) {
	return p.DeviceName
}

func (p *SessionInfo) GetUserAgent() (v string) {
	return p.UserAgent
}

func (p *SessionInfo) GetLoginIp() (v string) {
	return p.LoginIp
}

func (p *SessionInfo) GetLastIp() (v string) {
	return p.LastIp
}

func (p *SessionInfo) GetStatus() (v string) {
	return p.Status
}

func (p *SessionInfo) GetCurrent() (v bool) {
	return p.Current
}

func (p *SessionInfo) GetCreatedAt() (v int64) {
	return p.CreatedAt
}

func (p *SessionInfo) GetLastSeenAt() (v int64) {
	return p.LastSeenAt
}
func (p *SessionInfo) SetSessionId(val string) {
	p.SessionId = val
}
func (p *SessionInfo) SetDeviceId(val string) {
	p.DeviceId = val
}
func (p *SessionInfo) SetDeviceName(val string) {
	p.DeviceName = val
}
func (p *SessionInfo) SetUserAgent(val string) {
	p.UserAgent = val
}
func (p *SessionInfo) SetLoginIp(val string) {
	p.LoginIp = val
}
func (p *SessionInfo) SetLastIp(val string) {
	p.LastIp = val
}
func (p *SessionInfo) SetStatus(val string) {
	p.Status = val
}
func (p *SessionInfo) SetCurrent(val bool) {
	p.Current = val
}
func (p *SessionInfo) SetCreatedAt(val int64) {
	p.CreatedAt = val
}
func (p *SessionInfo) SetLastSeenAt(val int64) {
	p.LastSeenAt = val
}

func (p *SessionInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SessionInfo(%+v)", *p)
}

var fieldIDToName_SessionInfo = map[int16]string{
	1:  "session_id",
	2:  "device_id",
	3:  "device_name",
	4:  "user_agent",
	5:  "login_ip",
	6:  "last_ip",
	7:  "status",
	8:  "current",
	9:  "created_at",
	10: "last_seen_at",
}

type ListSessionsRequest struct {
	UserId           int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	CurrentSessionId string `thrift:"current_session_id,2" frugal:"2,default,string" json:"current_session_id"`
}

func NewListSessionsRequest() *ListSessionsRequest {
	return &ListSessionsRequest{}
}

func (p *ListSessionsRequest) InitDefault() {
}

func (p *ListSessionsRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *ListSessionsRequest) GetCurrentSessionId() (v string) {
	return p.CurrentSessionId
}
func (p *ListSessionsRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *ListSessionsRequest) SetCurrentSessionId(val string) {
	p.CurrentSessionId = val
}

func (p *ListSessionsRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListSessionsRequest(%+v)", *p)
}

var fieldIDToName_ListSessionsRequest = map[int16]string{
	1: "user_id",
	2: "current_session_id",
}

type ListSessionsResponse struct {
	Sessions []*SessionInfo `thrift:"sessions,1" frugal:"1,default,list<SessionInfo>" json:"sessions"`
}

func NewListSessionsResponse() *ListSessionsResponse {
	return &ListSessionsResponse{}
}

func (p *ListSessionsResponse) InitDefault() {
}

func (p *ListSessionsResponse) GetSessions() (v []*SessionInfo) {
	return p.Sessions
}
func (p *ListSessionsResponse) SetSessions(val []*SessionInfo) {
	p.Sessions = val
}

func (p *ListSessionsResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListSessionsResponse(%+v)", *p)
}

var fieldIDToName_ListSessionsResponse = map[int16]string{
	1: "sessions",
}

type RevokeSessionRequest struct {
	UserId    int64  `thrift:"user_id,1" frugal:"1,default,i64" json:"user_id"`
	SessionId string `thrift:"session_id,2" frugal:"2,default,string" json:"session_id"`
	Password  string `thrift:"password,3" frugal:"3,default,string" json:"password"`
}

func NewRevokeSessionRequest() *RevokeSessionRequest {
	return &RevokeSessionRequest{}
}

func (p *RevokeSessionRequest) InitDefault() {
}

func (p *RevokeSessionRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *RevokeSessionRequest) GetSessionId() (v string) {
	return p.SessionId
}

func (p *RevokeSessionRequest) GetPassword() (v string) {
	return p.Password
}
func (p *RevokeSessionRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *RevokeSessionRequest) SetSessionId(val string) {
	p.SessionId = val
}
func (p *RevokeSessionRequest) SetPassword(val string) {
	p.Password = val
}

func (p *RevokeSessionRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RevokeSessionRequest(%+v)", *p)
}

var fieldIDToName_RevokeSessionRequest = map[int16]string{
	1: "user_id",
	2: "session_id",
	3: "password",
}

type AuthService interface {
	Login(ctx context.Context, req *LoginRequest) (r *TokenPair, err error)

	RefreshToken(ctx context.Context, req *RefreshTokenRequest) (r *TokenPair, err error)

	ValidateToken(ctx context.Context, req *ValidateTokenRequest) (r *ValidateTokenResponse, err error)

	Logout(ctx context.Context, req *LogoutRequest) (r *CommonResponse, err error)

	LogoutAll(ctx context.Context, req *LogoutAllRequest) (r *CommonResponse, err error)

	ListSessions(ctx context.Context, req *ListSessionsRequest) (r *ListSessionsResponse, err error)

	RevokeSession(ctx context.Context, req *RevokeSessionRequest) (r *CommonResponse, err error)
}

type AuthServiceLoginArgs struct {
	Req *LoginRequest `thrift:"req,1" frugal:"1,default,LoginRequest" json:"req"`
}

func NewAuthServiceLoginArgs() *AuthServiceLoginArgs {
	return &AuthServiceLoginArgs{}
}

func (p *AuthServiceLoginArgs) InitDefault() {
}

var AuthServiceLoginArgs_Req_DEFAULT *LoginRequest

func (p *AuthServiceLoginArgs) GetReq() (v *LoginRequest) {
	if !p.IsSetReq() {
		return AuthServiceLoginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AuthServiceLoginArgs) SetReq(val *LoginRequest) {
	p.Req = val
}

func (p *AuthServiceLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AuthServiceLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceLoginArgs(%+v)", *p)
}

var fieldIDToName_AuthServiceLoginArgs = map[int16]string{
	1: "req",
}

type AuthServiceLoginResult struct {
	Success *TokenPair `thrift:"success,0,optional" frugal:"0,optional,TokenPair" json:"success,omitempty"`
}

func NewAuthServiceLoginResult() *AuthServiceLoginResult {
	return &AuthServiceLoginResult{}
}

func (p *AuthServiceLoginResult) InitDefault() {
}

var AuthServiceLoginResult_Success_DEFAULT *TokenPair

func (p *AuthServiceLoginResult) GetSuccess() (v *TokenPair) {
	if !p.IsSetSuccess() {
		return AuthServiceLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AuthServiceLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*TokenPair)
}

func (p *AuthServiceLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AuthServiceLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceLoginResult(%+v)", *p)
}

var fieldIDToName_AuthServiceLoginResult = map[int16]string{
	0: "success",
}

type AuthServiceRefreshTokenArgs struct {
	Req *RefreshTokenRequest `thrift:"req,1" frugal:"1,default,RefreshTokenRequest" json:"req"`
}

func NewAuthServiceRefreshTokenArgs() *AuthServiceRefreshTokenArgs {
	return &AuthServiceRefreshTokenArgs{}
}

func (p *AuthServiceRefreshTokenArgs) InitDefault() {
}

var AuthServiceRefreshTokenArgs_Req_DEFAULT *RefreshTokenRequest

func (p *AuthServiceRefreshTokenArgs) GetReq() (v *RefreshTokenRequest) {
	if !p.IsSetReq() {
		return AuthServiceRefreshTokenArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AuthServiceRefreshTokenArgs) SetReq(val *RefreshTokenRequest) {
	p.Req = val
}

func (p *AuthServiceRefreshTokenArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AuthServiceRefreshTokenArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceRefreshTokenArgs(%+v)", *p)
}

var fieldIDToName_AuthServiceRefreshTokenArgs = map[int16]string{
	1: "req",
}

type AuthServiceRefreshTokenResult struct {
	Success *TokenPair `thrift:"success,0,optional" frugal:"0,optional,TokenPair" json:"success,omitempty"`
}

func NewAuthServiceRefreshTokenResult() *AuthServiceRefreshTokenResult {
	return &AuthServiceRefreshTokenResult{}
}

func (p *AuthServiceRefreshTokenResult) InitDefault() {
}

var AuthServiceRefreshTokenResult_Success_DEFAULT *TokenPair

func (p *AuthServiceRefreshTokenResult) GetSuccess() (v *TokenPair) {
	if !p.IsSetSuccess() {
		return AuthServiceRefreshTokenResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AuthServiceRefreshTokenResult) SetSuccess(x interface{}) {
	p.Success = x.(*TokenPair)
}

func (p *AuthServiceRefreshTokenResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AuthServiceRefreshTokenResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceRefreshTokenResult(%+v)", *p)
}

var fieldIDToName_AuthServiceRefreshTokenResult = map[int16]string{
	0: "success",
}

type AuthServiceValidateTokenArgs struct {
	Req *ValidateTokenRequest `thrift:"req,1" frugal:"1,default,ValidateTokenRequest" json:"req"`
}

func NewAuthServiceValidateTokenArgs() *AuthServiceValidateTokenArgs {
	return &AuthServiceValidateTokenArgs{}
}

func (p *AuthServiceValidateTokenArgs) InitDefault() {
}

var AuthServiceValidateTokenArgs_Req_DEFAULT *ValidateTokenRequest

func (p *AuthServiceValidateTokenArgs) GetReq() (v *ValidateTokenRequest) {
	if !p.IsSetReq() {
		return AuthServiceValidateTokenArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AuthServiceValidateTokenArgs) SetReq(val *ValidateTokenRequest) {
	p.Req = val
}

func (p *AuthServiceValidateTokenArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AuthServiceValidateTokenArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceValidateTokenArgs(%+v)", *p)
}

var fieldIDToName_AuthServiceValidateTokenArgs = map[int16]string{
	1: "req",
}

type AuthServiceValidateTokenResult struct {
	Success *ValidateTokenResponse `thrift:"success,0,optional" frugal:"0,optional,ValidateTokenResponse" json:"success,omitempty"`
}

func NewAuthServiceValidateTokenResult() *AuthServiceValidateTokenResult {
	return &AuthServiceValidateTokenResult{}
}

func (p *AuthServiceValidateTokenResult) InitDefault() {
}

var AuthServiceValidateTokenResult_Success_DEFAULT *ValidateTokenResponse

func (p *AuthServiceValidateTokenResult) GetSuccess() (v *ValidateTokenResponse) {
	if !p.IsSetSuccess() {
		return AuthServiceValidateTokenResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AuthServiceValidateTokenResult) SetSuccess(x interface{}) {
	p.Success = x.(*ValidateTokenResponse)
}

func (p *AuthServiceValidateTokenResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AuthServiceValidateTokenResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceValidateTokenResult(%+v)", *p)
}

var fieldIDToName_AuthServiceValidateTokenResult = map[int16]string{
	0: "success",
}

type AuthServiceLogoutArgs struct {
	Req *LogoutRequest `thrift:"req,1" frugal:"1,default,LogoutRequest" json:"req"`
}

func NewAuthServiceLogoutArgs() *AuthServiceLogoutArgs {
	return &AuthServiceLogoutArgs{}
}

func (p *AuthServiceLogoutArgs) InitDefault() {
}

var AuthServiceLogoutArgs_Req_DEFAULT *LogoutRequest

func (p *AuthServiceLogoutArgs) GetReq() (v *LogoutRequest) {
	if !p.IsSetReq() {
		return AuthServiceLogoutArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AuthServiceLogoutArgs) SetReq(val *LogoutRequest) {
	p.Req = val
}

func (p *AuthServiceLogoutArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AuthServiceLogoutArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceLogoutArgs(%+v)", *p)
}

var fieldIDToName_AuthServiceLogoutArgs = map[int16]string{
	1: "req",
}

type AuthServiceLogoutResult struct {
	Success *CommonResponse `thrift:"success,0,optional" frugal:"0,optional,CommonResponse" json:"success,omitempty"`
}

func NewAuthServiceLogoutResult() *AuthServiceLogoutResult {
	return &AuthServiceLogoutResult{}
}

func (p *AuthServiceLogoutResult) InitDefault() {
}

var AuthServiceLogoutResult_Success_DEFAULT *CommonResponse

func (p *AuthServiceLogoutResult) GetSuccess() (v *CommonResponse) {
	if !p.IsSetSuccess() {
		return AuthServiceLogoutResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AuthServiceLogoutResult) SetSuccess(x interface{}) {
	p.Success = x.(*CommonResponse)
}

func (p *AuthServiceLogoutResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AuthServiceLogoutResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceLogoutResult(%+v)", *p)
}

var fieldIDToName_AuthServiceLogoutResult = map[int16]string{
	0: "success",
}

type AuthServiceLogoutAllArgs struct {
	Req *LogoutAllRequest `thrift:"req,1" frugal:"1,default,LogoutAllRequest" json:"req"`
}

func NewAuthServiceLogoutAllArgs() *AuthServiceLogoutAllArgs {
	return &AuthServiceLogoutAllArgs{}
}

func (p *AuthServiceLogoutAllArgs) InitDefault() {
}

var AuthServiceLogoutAllArgs_Req_DEFAULT *LogoutAllRequest

func (p *AuthServiceLogoutAllArgs) GetReq() (v *LogoutAllRequest) {
	if !p.IsSetReq() {
		return AuthServiceLogoutAllArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AuthServiceLogoutAllArgs) SetReq(val *LogoutAllRequest) {
	p.Req = val
}

func (p *AuthServiceLogoutAllArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AuthServiceLogoutAllArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceLogoutAllArgs(%+v)", *p)
}

var fieldIDToName_AuthServiceLogoutAllArgs = map[int16]string{
	1: "req",
}

type AuthServiceLogoutAllResult struct {
	Success *CommonResponse `thrift:"success,0,optional" frugal:"0,optional,CommonResponse" json:"success,omitempty"`
}

func NewAuthServiceLogoutAllResult() *AuthServiceLogoutAllResult {
	return &AuthServiceLogoutAllResult{}
}

func (p *AuthServiceLogoutAllResult) InitDefault() {
}

var AuthServiceLogoutAllResult_Success_DEFAULT *CommonResponse

func (p *AuthServiceLogoutAllResult) GetSuccess() (v *CommonResponse) {
	if !p.IsSetSuccess() {
		return AuthServiceLogoutAllResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AuthServiceLogoutAllResult) SetSuccess(x interface{}) {
	p.Success = x.(*CommonResponse)
}

func (p *AuthServiceLogoutAllResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AuthServiceLogoutAllResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceLogoutAllResult(%+v)", *p)
}

var fieldIDToName_AuthServiceLogoutAllResult = map[int16]string{
	0: "success",
}

type AuthServiceListSessionsArgs struct {
	Req *ListSessionsRequest `thrift:"req,1" frugal:"1,default,ListSessionsRequest" json:"req"`
}

func NewAuthServiceListSessionsArgs() *AuthServiceListSessionsArgs {
	return &AuthServiceListSessionsArgs{}
}

func (p *AuthServiceListSessionsArgs) InitDefault() {
}

var AuthServiceListSessionsArgs_Req_DEFAULT *ListSessionsRequest

func (p *AuthServiceListSessionsArgs) GetReq() (v *ListSessionsRequest) {
	if !p.IsSetReq() {
		return AuthServiceListSessionsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AuthServiceListSessionsArgs) SetReq(val *ListSessionsRequest) {
	p.Req = val
}

func (p *AuthServiceListSessionsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AuthServiceListSessionsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceListSessionsArgs(%+v)", *p)
}

var fieldIDToName_AuthServiceListSessionsArgs = map[int16]string{
	1: "req",
}

type AuthServiceListSessionsResult struct {
	Success *ListSessionsResponse `thrift:"success,0,optional" frugal:"0,optional,ListSessionsResponse" json:"success,omitempty"`
}

func NewAuthServiceListSessionsResult() *AuthServiceListSessionsResult {
	return &AuthServiceListSessionsResult{}
}

func (p *AuthServiceListSessionsResult) InitDefault() {
}

var AuthServiceListSessionsResult_Success_DEFAULT *ListSessionsResponse

func (p *AuthServiceListSessionsResult) GetSuccess() (v *ListSessionsResponse) {
	if !p.IsSetSuccess() {
		return AuthServiceListSessionsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AuthServiceListSessionsResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListSessionsResponse)
}

func (p *AuthServiceListSessionsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AuthServiceListSessionsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceListSessionsResult(%+v)", *p)
}

var fieldIDToName_AuthServiceListSessionsResult = map[int16]string{
	0: "success",
}

type AuthServiceRevokeSessionArgs struct {
	Req *RevokeSessionRequest `thrift:"req,1" frugal:"1,default,RevokeSessionRequest" json:"req"`
}

func NewAuthServiceRevokeSessionArgs() *AuthServiceRevokeSessionArgs {
	return &AuthServiceRevokeSessionArgs{}
}

func (p *AuthServiceRevokeSessionArgs) InitDefault() {
}

var AuthServiceRevokeSessionArgs_Req_DEFAULT *RevokeSessionRequest

func (p *AuthServiceRevokeSessionArgs) GetReq() (v *RevokeSessionRequest) {
	if !p.IsSetReq() {
		return AuthServiceRevokeSessionArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AuthServiceRevokeSessionArgs) SetReq(val *RevokeSessionRequest) {
	p.Req = val
}

func (p *AuthServiceRevokeSessionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AuthServiceRevokeSessionArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceRevokeSessionArgs(%+v)", *p)
}

var fieldIDToName_AuthServiceRevokeSessionArgs = map[int16]string{
	1: "req",
}

type AuthServiceRevokeSessionResult struct {
	Success *CommonResponse `thrift:"success,0,optional" frugal:"0,optional,CommonResponse" json:"success,omitempty"`
}

func NewAuthServiceRevokeSessionResult() *AuthServiceRevokeSessionResult {
	return &AuthServiceRevokeSessionResult{}
}

func (p *AuthServiceRevokeSessionResult) InitDefault() {
}

var AuthServiceRevokeSessionResult_Success_DEFAULT *CommonResponse

func (p *AuthServiceRevokeSessionResult) GetSuccess() (v *CommonResponse) {
	if !p.IsSetSuccess() {
		return AuthServiceRevokeSessionResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AuthServiceRevokeSessionResult) SetSuccess(x interface{}) {
	p.Success = x.(*CommonResponse)
}

func (p *AuthServiceRevokeSessionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AuthServiceRevokeSessionResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceRevokeSessionResult(%+v)", *p)
}

var fieldIDToName_AuthServiceRevokeSessionResult = map[int16]string{
	0: "success",
}
